### ISSUE TITLE
AttributeError while running train.py

### ISSUE THREAD

**Issue by ZheMann** [rkfg/gpt-2#2]
I'm running into trouble while trying to train the gpt-2 model on my own (Dutch) corpus.

I first create the files `hparams.json`, `sp.model` and `sp.vocab` by executing the following command:
`!PYTHONPATH=src ./scripts/createspmodel.sh combined_wo_startendtag.txt 64000`

Then, after copying those files to `models/117M/` I execute the following command:
`!PYTHONPATH=src ./train.py --dataset /content/gpt-2/combined_wo_startendtag.txt --model_name '117M' --restore_from 'latest'`

However, without much luck because when calling `encoder.get_encoder(args.model_name)` an `AttributeError` occurs, saying that module `sentencepiece` has no attribute `SentencePieceProcessor`. Stacktrace:  
```
Traceback (most recent call last):
  File "./train.py", line 208, in <module>
    main()
  File "./train.py", line 48, in main
    enc = encoder.get_encoder(args.model_name)
  File "/content/gpt-2/src/encoder_sp.py", line 17, in get_encoder
    return Encoder(os.path.join('models', model_name, 'sp.model'))
  File "/content/gpt-2/src/encoder_sp.py", line 7, in __init__
    self.sp = spm.SentencePieceProcessor()
AttributeError: module 'sentencepiece' has no attribute 'SentencePieceProcessor'
```
Do you have any idea how to fix this problem? As I don't have GPU, I'm trying to run this repo in colab.google.com, could this be the reason?

**Comment by rkfg** [comment]
I guess you've figured it out yourself but for the future reference: you need to install `sentencepiece` python library, for example with `pip3 install sentencepiece`. I tried to make this all work on colab and it *kinda* worked but it's such a bother to execute many commands by hand and also consider that 24 hours limit. It might be okay to check if it works at all but to get any meaningful results you'd need it to run for *days* on a pretty high-end hardware. Don't expect the original GPT-2 text quality even after running it for a week on a GTX 1070 for example. The text will be readable but not as coherent or interesting.
